function addons = SMASHAddons()
    addons = [
        "Curve Fitting Toolbox",...
        "flattenMaskOverlay",...
        "Statistics and Machine Learning Toolbox",...
        "Image Processing Toolbox",...
        "Convert between RGB and Color Names",...
    ];
end

